<?php

declare(strict_types=1);

namespace MykeMeynell\Laravel\Decorators\Decorators;

use Attribute;
use Illuminate\Support\Facades\RateLimiter;
use MykeMeynell\Laravel\Decorators\Contracts\MethodDecorator;
use RuntimeException;

/**
 * Throttles decorated method calls using Laravel's rate limiter.
 *
 * Argument-specific rate keys are generated by default so separate invocation
 * payloads are tracked independently. Callers can also force a fixed key to
 * share the same bucket across all invocations.
 *
 * @author Myke Meynell
 * @license MIT
 *
 * @since 1.0.0
 */
#[Attribute(Attribute::TARGET_METHOD)]
final class RateLimit implements MethodDecorator
{
    /**
     * Create a new rate limit decorator.
     *
     * @param  int  $maxAttempts  Maximum allowed calls before blocking.
     * @param  int  $decaySeconds  Duration of the rate limit window in seconds.
     * @param  string|null  $key  Optional fixed bucket identifier.
     * @param  string  $prefix  Prefix applied to generated keys.
     * @return void
     */
    public function __construct(
        private readonly int $maxAttempts = 60,
        private readonly int $decaySeconds = 60,
        private readonly ?string $key = null,
        private readonly string $prefix = 'decorator:rate',
    ) {}

    /**
     * {@inheritdoc}
     */
    public function wrap(callable $next, array $context = []): callable
    {
        return function (array $args) use ($next, $context): mixed {
            $key = $this->resolveKey($args, $context);

            if (RateLimiter::tooManyAttempts($key, $this->maxAttempts)) {
                $seconds = RateLimiter::availableIn($key);

                throw new RuntimeException(
                    "Rate limit exceeded. Try again in {$seconds} second(s).",
                );
            }

            RateLimiter::hit($key, $this->decaySeconds);

            return $next($args);
        };
    }

    /**
     * Build the rate limiter bucket key for the current invocation.
     *
     * @param  array<int, mixed>  $args  Invocation arguments.
     * @param  array<string, mixed>  $context  Method context values.
     * @return string Rate limiter key.
     */
    private function resolveKey(array $args, array $context): string
    {
        if ($this->key !== null) {
            return $this->prefix.':'.$this->key;
        }

        $callable = (string) ($context['callable'] ?? 'unknown::method');

        return $this->prefix.':'.sha1(serialize([$callable, $args]));
    }
}
